language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  # Install the codecov pip dependency
  - pip install pytest-cov

# command to run tests
script:
  - py.test --cov=menuP27a tests/

after_success:
  - codecov
